#!/bin/bash

set -o errexit

export SBT_OPTS="-Dspecs2.color=false -Dsbt.log.format=true -Dsbt.log.noformat=true \
 -Xms1024M -Xmx3096M -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -XX:+UseParNewGC \
 -XX:PermSize=1024M -XX:MaxPermSize=2048M -Dtest.port=9006 \
 -Dws.timeout.request=30000 -DpaymentSolve.ms.requesttimeout=65000 -DvrmAssignEligibility.requestTimeout=30000 \
 -DvrmAssignFulfil.requestTimeout=30000 -DtimeoutInMillisSoap=30000 -Dspray.can.server.request-timeout=30s -DspanScaleFactor=5.0 $SBT_OPTS"
